### ISSUE TITLE
Error opening a save file

### ISSUE THREAD

**Issue by stannisthemannis315** [FromDarkHell/BL3SaveEditor#17]
I tried opening my Steam Amara save file and I got an error titled "Save Parse Exception." Opening other character save files and my profile save file worked just fine so it's just my Amara that has this issue. I've attached an image of the error message, the Amara save file, and images of each tab of the save editor after trying to open it. After I click OK on the message, I can look through the tabs and majority of it is empty. It recognizes that it's my Amara save and has the playtime on it but every thing else is blank. No money, weapons, fast travel, etc.
[BL3Save.zip](https://github.com/FromDarkHell/BL3SaveEditor/files/7494112/BL3Save.zip)

**Comment by FromDarkHell** [comment]
Fixed in the most recent update: [1.1.2](https://github.com/FromDarkHell/BL3SaveEditor/releases/tag/v1.1.2).
This had to do with the skin color picker and how it handled default (transparent) colors, if I have more issues with this feature, I may just rip it out (we'll see).
