### ISSUE TITLE
Unable to open ps4 save files

### ISSUE THREAD

**Issue by sonicxd983** [FromDarkHell/BL3SaveEditor#18]
I saw that this editor supported ps4 save files but when i import my ps4 save to my computer the editor does not recognize it at all. Idk if I am doing something wrong or not but can you please let me know and if I am being stupid on something can I be helped to better understand it

**Comment by FromDarkHell** [comment]
The save file has to be decrypted (I do not know nor care to know how to decrypt a PS4 save, I literally don't even own one).

You also need to select the platform when you load the file.
![image](https://user-images.githubusercontent.com/9018764/141214355-1f579108-0198-4239-8a60-76a7f16864a8.png)
