### ISSUE TITLE
"Profile" tab not working

### ISSUE THREAD

**Issue by WaveHolder** [FromDarkHell/BL3SaveEditor#25]
I´m sorry, but why is the "profile" tab blacked out ?
I watched a few videos and most of them are able to access this feature.

Thank you for any valid response.

**Comment by FromDarkHell** [comment]
You need to have a profile open in order to use it.

**Comment by WaveHolder** [comment]
> 

I´m sorry, can you elaborate? 
I think you misunderstand, every single OTHER tab is working, just the "profile tab" is not.

How else do I load a profile if not: "OPEN" > 76561198076471802 > x.sav
???
![image](https://user-images.githubusercontent.com/100498647/156451399-a1fa9ccf-b9ce-4ba9-93e7-b999bf0e775e.png)
 ONLY the PROFILE tab is greyed out.

**Comment by FromDarkHell** [comment]
You are not opening a profile. You are opening a save file. These are separate things.
![image](https://user-images.githubusercontent.com/9018764/156690138-5589e0ce-09ea-47c0-aa26-b8703fb429d7.png)

**Comment by WaveHolder** [comment]
what is the "profile.sav" location ?
![image](https://user-images.githubusercontent.com/100498647/156903349-43992cec-947d-4042-a951-f9fcd350bcec.png)
