### ISSUE TITLE
DLC 2 Glutton's Gamble items

### ISSUE THREAD

**Issue by xKellx** [FromDarkHell/BL3SaveEditor#32]
New DLCs dropped for Tiny Tina's Wonderlands with a handful of new items. It would be great if you added those!

**Comment by FromDarkHell** [comment]
You'll notice that this is a BL3 save editor.
You're probably looking to make an issue for the actual wonderlands save editor which is not on this repo, but [Jokarwent's fork](https://github.com/jokarwent/BL3SaveEditor/tree/wonderlands). You will have to contact them.
