### ISSUE TITLE
Decrypted PS4 BogoCrypt Keys

### ISSUE THREAD

**Issue by xcier** [FromDarkHell/BL3SaveEditor#7]
[Character.txt](https://github.com/FromDarkHell/BL3SaveEditor/files/7254416/Character.txt)
[Profile.txt](https://github.com/FromDarkHell/BL3SaveEditor/files/7254417/Profile.txt)

Please add PS4 decrypted option to save output/input.

**Comment by FromDarkHell** [comment]
Closed with the release of v1.1.0 and [3c3cf9c](https://github.com/FromDarkHell/BL3SaveEditor/commit/46b5ce573cc26d4ec120d26da25d72f4850d8a73)
