### ISSUE TITLE
[Feature Request] customizable Mayhem modifiers

### ISSUE THREAD

**Issue by nicko996** [FromDarkHell/BL3SaveEditor#8]
Don't know if it's possible but it would be useful to being able to choose the mayhem modifiers for each mayhem level.

**Comment by FromDarkHell** [comment]
So I pretty much can't implement what you're thinking at all.
Short explanation: When the game stores Mayhem data, it only stores the *seed* of the Mayhem. (If you've played Minecraft, imagine how worlds have random seeds and such). So in reality, I can't explicitly have a "pick and choose" style list of all of the possible mayhem modifiers (plus, if they add/remove mayhem modifiers (even via hotfixes!), it completely changes).

Currently the Mayhem Seed *is* editable via the `GameStateSaveDataForPlaythroughs` field in the `Raw` tab though.
Personally the best I can do is make that seed more accessible to the layman (i.e. `General` tab), but given how volatile the Mayhem Seeds are (i.e. GBX adds/removes a modifer, then everyone complains **mayhem seed no worky**), it might not be the best to share them around for most people.

![image](https://user-images.githubusercontent.com/9018764/135765653-aaf11769-c0bd-4002-97e7-c9741db1b84e.png)
